"""add certification_level column

Revision ID: 8138c8cbf5d4
Revises: ac4095016bbc
Create Date: 2026-08-26 14:53:29.868032

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '8138c8cbf5d4'
down_revision: str | None = 'ac4095016bbc'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'assessments', sa.Column('certification_level', sa.String(length=20), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assessments', 'certification_level')
    # ### end Alembic commands ###
