"""add security_score column

Revision ID: ac4095016bbc
Revises: 1a3d5f7aa8be
Create Date: 2026-08-26 14:24:29.269732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac4095016bbc'
down_revision: Union[str, None] = '1a3d5f7aa8be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assessments', sa.Column('security_score', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assessments', 'security_score')
    # ### end Alembic commands ###
