"""add created_at to assessments

Revision ID: b7118f4be16c
Revises: 8138c8cbf5d4
Create Date: 2026-08-26 15:07:21.301909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7118f4be16c'
down_revision: Union[str, None] = '8138c8cbf5d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default backfills existing rows (this is a dev DB with manual test data);
    # the app itself always sets created_at client-side via AssessmentModel's default.
    op.add_column(
        'assessments',
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text('now()'),
        ),
    )
    op.alter_column('assessments', 'created_at', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assessments', 'created_at')
    # ### end Alembic commands ###
