"""add ai_trust_score column

Revision ID: fa2593a3dc07
Revises: f049e37de71e
Create Date: 2026-08-26 16:33:10.738153

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'fa2593a3dc07'
down_revision: str | None = 'f049e37de71e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assessments', sa.Column('ai_trust_score', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assessments', 'ai_trust_score')
    # ### end Alembic commands ###
